apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpro-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/somnathp2757/argocd-project-for-k8s.git
    targetRevision: HEAD
    path: helm/vprofilecharts
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
